name: Setup VLLM
description: Start VLLM
runs:
  using: "composite"
  steps:
    - name: Start VLLM
      shell: bash
      run: |
        # Start vllm container (automatically pulls correct architecture via QEMU)
        docker run -d \
          --name vllm \
          --privileged=true \
          --net=host \
          --platform linux/amd64 \
          quay.io/higginsd/vllm-cpu:65393ee064-qwen3 \
          --host 0.0.0.0 \
          --port 8000 \
          --enable-auto-tool-choice \
          --tool-call-parser hermes \
          --model /root/.cache/Qwen3-0.6B \
          --served-model-name Qwen/Qwen3-0.6B \
          --max-model-len 8192

          # Wait for vllm to be ready (extended timeout for ARM64/QEMU emulation)
          echo "Waiting for vllm to be ready..."
          timeout 1800 bash -c 'until curl -fsS http://localhost:8000/health >/dev/null; do
            echo "Waiting for vllm..."
            sleep 5
          done'
